<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<div class="bestseller-products">
<div class="bestseller-products-inner">

<div class="category-title"><h2><a href="<?php echo $this->getUrl('') ?>bestseller"><?php echo $this->getHeading(); ?></a></h2></div>

<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
 	
	<?php $_collectionSize = $_productCollection->count() ?>
	
	<?php 
		$sliderFor = 5;
		$productCount = $_collectionSize; 
	?>
	
	<?php if ($productCount >= $sliderFor): ?>
		<div class="customNavigation">
			<a class="btn prev">prev</a>
			<a class="btn next">next</a>
		</div>	
	<?php endif; ?>	

		<ul class="<?php if ($productCount >= $sliderFor){?>product-carousel<?php }else{?>products-grid<?php }?>" id="<?php if ($productCount >= $sliderFor){?>bestseller-carousel<?php }else{?>bestseller-grid<?php }?>">
				
    	<?php $i=0; foreach ($_productCollection as $_product):  $i++;?>
		
		<?php $_product = Mage::getModel('catalog/product')->load($_product->getEntityId()); ?>

           <li class="item <?php if ($productCount >= $sliderFor){?>slider-item<?php }else{?>product-items<?php }?>">
				<div class="product-block">
				<div class="product-block-inner">
					<div class="product-image-block-inner">	
						<div class="product-image-block">   
					<?php if($this->helper('framework')->isNewProduct($_product)):?>
						<div class="new-label"><?php echo $this->__('New') ?></div>
					<?php endif; ?>
					
					
					
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
	 <?php 
			   $productId = $_product->getId();
				$_product = Mage::getModel('catalog/product')->load($productId);
				
			  ?>
		<img class="remover-image" id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(218,287); ?>" alt="" />
		<img  class="hover-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(218,287); ?>" width="218" height="287" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />
				</a>
					
					
					</div>
					   <div class="product_hover-block">
					<div class="actions">
						<?php if($_product->isSaleable()): ?>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?> 
						  
						  <ul class="add-to-links">
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    	</ul>                 
					</div>
					</div>
					</div>
					 <div class="product_desc">
						<h2 class="product-name" ><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName())?></a></h2> 
				
                	<?php echo $this->getPriceHtml($_product, true) ?> 
				  	<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
				 
						
						<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
					<div class="sale-label"><?php echo $this->__('Sale') ?></div>
				<?php endif; ?>
				 		
					</div> 
					
				</div><!-- End div class product-block-->
				</div><!-- End div class product-block-inner -->
            </li>

        <?php endforeach ?>
		</ul>
		
		<span style="display: none; visibility: hidden;" class="bestseller_default_width"></span>
<?php endif; ?>
</div>
</div>