
<?php if (($_products = $this->getSpecialProductCollection()) && $_products->getSize()): ?>
<div class="block block-related">
    <div class="block-title">
        <strong><span><?php echo $this->getSidebarHeading(); ?></span></strong>
    </div>
    <div class="block-content">      
        <ol class="mini-products-list" id="block-specialproducts">
        <?php foreach ($_products as $_item): ?>
            <li class="item">                
                <div class="product"  style="margin-left: 0px;">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(55,72) ?>" width="55" height="72" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>					
                    <div class="product-details">
                    <p class="product-name">
					
						<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" >
				 <?php $str = strlen($this->escapeHtml($_item->getName()));
				
				  if($str <= 14 ){ 
			echo $this->escapeHtml($_item->getName()); ?>
				 <?php }else{
				   echo substr($this->escapeHtml($_item->getName()),0,12) ."..";
				 
				 }?>
				 
				</a>
					
					</p>
					
					
				<div class="price-box">
						<?php 
							if($_item->getFinalPrice() < $_item->getPrice()){
							
						?>
					<span class="price old-price"><?php echo Mage::helper('core')->currency($_item->price, true, false); ?></span>
					<span class="price special-price">	<?php echo Mage::helper('core')->currency($_item->getFinalPrice(), true, false); ?> </span>
					
					<?php }else{ ?>
					
					<span class="price">	<?php echo Mage::helper('core')->currency($_item->getFinalPrice(), true, false); ?> </span>
					<?php } ?>
					</div>
				
					<?php if($_item->isSaleable()): ?>
					<p><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->__('Add to Cart') ?>"  rel="nofollow" class="addto-cart"><?php echo $this->__('Add to Cart') ?></a></p>
					<?php endif; ?>
					
                    </div>
					
                </div>
            </li>
        <?php endforeach ?>
        </ol>
		<div class="actions"><a href="<?php echo $this->getUrl('') ?>specialproducts"><?php echo $this->__('See All') ?></a></div>
    <script type="text/javascript">decorateList('block-specialproducts', 'none-recursive')</script>
  </div>    
</div>
<?php endif ?>

